[cli]
installer = "internal"
auto_update = true

[ui]
max_thoughts_width = 120
fork_secondary_model = "grok-build"
yolo = false
compact_mode = false
permission_mode = "always-approve"
theme = "auto"

[plugins]
disabled = []
enabled = ["user/127bfd3d/slack"]

[marketplace]
official_marketplace_auto_installed = true
default_skills_installs_purged = true

[[marketplace.sources]]
name = "xAI Official"
git = "https://github.com/xai-org/plugin-marketplace.git"

[mcp_servers.judgment-mcp]
url = "https://mcp.judgmentlabs.ai"
enabled = true
